- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest


- name: Remove previous content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy Roboshop Content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes